In [1]:
import numpy as np
import pandas as pd

def system_over_years(graph, years):
    return sum([np.linalg.matrix_power(graph, i) for i in range(years + 1)])
        

def simulate_impulse(graph, impulses, years):
    if len(impulses) != len(graph):
        raise ValueError("Sizes don't match!")
    
    # print(system_over_years(graph, years))
    return impulses.dot(system_over_years(graph, years))
    

graph = pd.read_csv('graph.csv', sep=';', index_col=0, header=0)
print(graph)
print('--------------------------------------------------')
print(f'Enter impulse array using Python syntax, like\n[{", ".join(list(graph))}]:')
l = eval(input())
years = int(input("Enter how many years to simulate through:"))

    РЕ  РГ  ЗП  ЗО  ІВ  ПЗ  ВЗ  ЗР  ЗТ  ЕС  ЗН  ПН
РЕ   0   0   1   1   1   0   0   0   0   0   0   0
РГ   0   0   0   1   1   0   0   0   0   0   0   0
ЗП   0   0   0   0   0   1   0   1   0   0   0   0
ЗО   0   0   0   0   0   1   0   1   1   0   0   0
ІВ   0   0   0   0   0   1   1   0   0   0   0   0
ПЗ   0   0   0   0   0   0   1   0   0  -1   0   0
ВЗ   0   0   0   0   0   0   0   1   1  -1   0   0
ЗР   0   0   0   0   0   0   0   0   0   0  -1   0
ЗТ   0   0   0   0   0   0   0   0   0   0  -1   0
ЕС   0   0   0   0   0   0   0   0   0   0   1   0
ЗН   0   0   0   0   0   0   0   0   0   0   0   1
ПН   1   1   0   0   0   0   0   0   0   0   0   0
--------------------------------------------------
Enter impulse array using Python syntax, like
[РЕ, РГ, ЗП, ЗО, ІВ, ПЗ, ВЗ, ЗР, ЗТ, ЕС, ЗН, ПН]:


 [-0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Enter how many years to simulate through: 5


In [2]:
print('--------------------------------------------------')
print()
for i in range(1, years + 1):
    s = '+'.join([f'A^{j}' for j in range(i + 1)])
    print(f"{s}\n{system_over_years(graph, i)}\n")

--------------------------------------------------

A^0+A^1
[[ 1  0  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  1  0  0  0  0]
 [ 0  0  0  1  0  1  0  1  1  0  0  0]
 [ 0  0  0  0  1  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  0  0 -1  0  0]
 [ 0  0  0  0  0  0  1  1  1 -1  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 -1  0]
 [ 0  0  0  0  0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1]
 [ 1  1  0  0  0  0  0  0  0  0  0  1]]

A^0+A^1+A^2
[[ 1  0  1  1  1  3  1  2  1  0  0  0]
 [ 0  1  0  1  1  2  1  1  1  0  0  0]
 [ 0  0  1  0  0  1  1  1  0 -1 -1  0]
 [ 0  0  0  1  0  1  1  1  1 -1 -2  0]
 [ 0  0  0  0  1  1  2  1  1 -2  0  0]
 [ 0  0  0  0  0  1  1  1  1 -2 -1  0]
 [ 0  0  0  0  0  0  1  1  1 -1 -3  0]
 [ 0  0  0  0  0  0  0  1  0  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  1  0 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  1  1  1]
 [ 1  1  0  0  0  0  0  0  0  0  1  1]
 [ 1  1  1  2  2  0  0  0  0 

In [2]:
print('--------------------------------------------------')
print("Development of the system over years:\n")

states_lists = [simulate_impulse(graph, np.array(l), i) for i in range(years + 1)]
states_df = pd.DataFrame(states_lists, columns=graph.columns)
states_df.index.rename('year', inplace=True)
print(states_df)

--------------------------------------------------
Development of the system over years:

        РЕ    РГ    ЗП    ЗО    ІВ    ПЗ    ВЗ    ЗР    ЗТ    ЕС    ЗН    ПН
year                                                                        
0    -0.05  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00
1    -0.05  0.00 -0.05 -0.05 -0.05  0.00  0.00  0.00  0.00  0.00  0.00  0.00
2    -0.05  0.00 -0.05 -0.05 -0.05 -0.15 -0.05 -0.10 -0.05  0.00  0.00  0.00
3    -0.05  0.00 -0.05 -0.05 -0.05 -0.15 -0.20 -0.15 -0.10  0.20  0.15  0.00
4    -0.05  0.00 -0.05 -0.05 -0.05 -0.15 -0.20 -0.30 -0.25  0.35  0.45  0.15
5     0.10  0.15 -0.05 -0.05 -0.05 -0.15 -0.20 -0.30 -0.25  0.35  0.90  0.45
