In [1]:
import numpy as np
import pandas as pd


def comparison_matrix(cases):

    element_matrices = []
    for row in cases.values:
        matrix = np.array([[int(left >= right)
                            for right in row] for left in row])
        element_matrices.append(matrix)

    sum_matrix = sum(element_matrices)

    resulting_matrix = np.array(
        [[int(elem > len(cases.values) / 2.)
        for elem in row] for row in sum_matrix])

    return resulting_matrix, sum_matrix, element_matrices


cases = pd.read_csv("scenarios.csv", index_col=0,
                    header=0, sep=';', decimal=',')
print('--------------------------------------------------')
print(cases)
print('--------------------------------------------------')
resulting_matrix, sum_matrix, element_matrices = comparison_matrix(cases)

--------------------------------------------------
          "Зміна палива"  "Альт. енергетика"  "Електричні установки"
Показник                                                            
ЕС                   0.2                0.35                     0.2
ЗН                   0.5                0.90                     0.6
--------------------------------------------------


In [2]:
print('--------------------------------------------------')
print('Pair comparison:\n')
for i in range(len(cases.index.values)):
    print(f'{cases.index.values[i]}:\n{element_matrices[i]}\n')
    
print('--------------------------------------------------')

--------------------------------------------------
Pair comparison:

ЕС:
[[1 0 1]
 [1 1 1]
 [1 0 1]]

ЗН:
[[1 0 0]
 [1 1 1]
 [1 0 1]]

--------------------------------------------------


In [3]:
print('--------------------------------------------------')
print(f'Matrices sum:\n{sum_matrix}\n\nResulting matrix:\n{resulting_matrix}')
print('--------------------------------------------------')

--------------------------------------------------
Matrices sum:
[[2 0 1]
 [2 2 2]
 [2 0 2]]

Resulting matrix:
[[1 0 0]
 [1 1 1]
 [1 0 1]]
--------------------------------------------------


In [4]:
row_sums = [sum(row) for row in resulting_matrix]
sorted_results = sorted(zip(list(cases), row_sums), key=lambda k: k[1], reverse=True)

print('--------------------------------------------------')
print(f'Scenraios ordered from best to worst:')
for i, x in enumerate(sorted_results, 1):
    print(f'{i}. {x[0]} with {x[1]} point(s)')
print('--------------------------------------------------')

--------------------------------------------------
Scenraios ordered from best to worst:
1. "Альт. енергетика" with 3 point(s)
2. "Електричні установки" with 2 point(s)
3. "Зміна палива" with 1 point(s)
--------------------------------------------------
