In [6]:
import numpy as np
import pandas as pd


def comparison_matrix(cases):

    element_matrices = []
    for row in cases.values:
        matrix = np.array([[int(left >= right)
                            for right in row] for left in row])
        element_matrices.append(matrix)

    sum_matrix = sum(element_matrices)

    resulting_matrix = np.array(
        [[int(elem >= len(cases.values) / 2.)
        for elem in row] for row in sum_matrix])

    return resulting_matrix, sum_matrix, element_matrices


cases = pd.read_csv("scenarios.csv", index_col=0,
                    header=0, sep=';', decimal=',')
print('--------------------------------------------------')
print(cases)
print('--------------------------------------------------')
resulting_matrix, sum_matrix, element_matrices = comparison_matrix(cases)

--------------------------------------------------
          "Зміна палива"  "Альт. енергетика"  "Жорсткі ліміти"  \
Показник                                                         
СД                  0.10                0.25              0.25   
ЗН                  0.10                0.30              0.40   
ЯЖ                  0.05               -0.05              0.50   

          "Електричні установки"  
Показник                          
СД                          0.05  
ЗН                          0.10  
ЯЖ                          0.00  
--------------------------------------------------


In [7]:
print('--------------------------------------------------')
print('Pair comparison:\n')
for i in range(len(cases.index.values)):
    print(f'{cases.index.values[i]}:\n{element_matrices[i]}\n')
    
print('--------------------------------------------------')

--------------------------------------------------
Pair comparison:

СД:
[[1 0 0 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 1]]

ЗН:
[[1 0 0 1]
 [1 1 0 1]
 [1 1 1 1]
 [1 0 0 1]]

ЯЖ:
[[1 1 0 1]
 [0 1 0 0]
 [1 1 1 1]
 [0 1 0 1]]

--------------------------------------------------


In [8]:
print('--------------------------------------------------')
print(f'Matrices sum:\n{sum_matrix}\n\nResulting matrix:\n{resulting_matrix}')
print('--------------------------------------------------')

--------------------------------------------------
Matrices sum:
[[3 1 0 3]
 [2 3 1 2]
 [3 3 3 3]
 [1 1 0 3]]

Resulting matrix:
[[1 0 0 1]
 [1 1 0 1]
 [1 1 1 1]
 [0 0 0 1]]
--------------------------------------------------


In [5]:
row_sums = [sum(row) for row in resulting_matrix]
sorted_results = sorted(zip(list(cases), row_sums), key=lambda k: k[1], reverse=True)

print('--------------------------------------------------')
print(f'Scenraios ordered from best to worst:')
for i, x in enumerate(sorted_results, 1):
    print(f'{i}. {x[0]} with {x[1]} point(s)')
print('--------------------------------------------------')

--------------------------------------------------
Scenraios ordered from best to worst:
1. "Жорсткі ліміти" with 4 point(s)
2. "Альт. енергетика" with 3 point(s)
3. "Зміна палива" with 2 point(s)
4. "Електричні установки" with 1 point(s)
--------------------------------------------------
